FROM node:22-bookworm-slim AS deps

WORKDIR /app/web

ENV NEXT_TELEMETRY_DISABLED=1

COPY web/package.json web/package-lock.json ./
RUN npm ci

FROM node:22-bookworm-slim AS builder

WORKDIR /app/web

ENV NEXT_TELEMETRY_DISABLED=1

# Next.js inlines NEXT_PUBLIC_* vars at build time, so they must be
# present during `npm run build`. Render passes env vars as build args.
ARG NEXT_PUBLIC_REOWN_PROJECT_ID
ENV NEXT_PUBLIC_REOWN_PROJECT_ID=$NEXT_PUBLIC_REOWN_PROJECT_ID
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_API_PROXY_URL
ENV NEXT_PUBLIC_API_PROXY_URL=$NEXT_PUBLIC_API_PROXY_URL
ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BASE_CHAIN_ID
ENV NEXT_PUBLIC_BASE_CHAIN_ID=$NEXT_PUBLIC_BASE_CHAIN_ID
ARG NEXT_PUBLIC_BASE_RPC_URL
ENV NEXT_PUBLIC_BASE_RPC_URL=$NEXT_PUBLIC_BASE_RPC_URL
ARG NEXT_PUBLIC_RELAY_TOKEN_ADDRESS
ENV NEXT_PUBLIC_RELAY_TOKEN_ADDRESS=$NEXT_PUBLIC_RELAY_TOKEN_ADDRESS
ARG NEXT_PUBLIC_RELAY_STAKING_ADDRESS
ENV NEXT_PUBLIC_RELAY_STAKING_ADDRESS=$NEXT_PUBLIC_RELAY_STAKING_ADDRESS
ARG NEXT_PUBLIC_MARKET_CORE_ADDRESS
ENV NEXT_PUBLIC_MARKET_CORE_ADDRESS=$NEXT_PUBLIC_MARKET_CORE_ADDRESS
ARG NEXT_PUBLIC_ORDER_BOOK_ADDRESS
ENV NEXT_PUBLIC_ORDER_BOOK_ADDRESS=$NEXT_PUBLIC_ORDER_BOOK_ADDRESS
ARG NEXT_PUBLIC_AGENT_RUNTIME_ADDRESS
ENV NEXT_PUBLIC_AGENT_RUNTIME_ADDRESS=$NEXT_PUBLIC_AGENT_RUNTIME_ADDRESS
ARG NEXT_PUBLIC_COLLATERAL_TOKEN_ADDRESS
ENV NEXT_PUBLIC_COLLATERAL_TOKEN_ADDRESS=$NEXT_PUBLIC_COLLATERAL_TOKEN_ADDRESS
ARG NEXT_PUBLIC_COLLATERAL_VAULT_ADDRESS
ENV NEXT_PUBLIC_COLLATERAL_VAULT_ADDRESS=$NEXT_PUBLIC_COLLATERAL_VAULT_ADDRESS

COPY --from=deps /app/web/node_modules ./node_modules
COPY web ./

RUN npm run build

FROM node:22-bookworm-slim AS runner

WORKDIR /app/web

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=10000

COPY --from=builder /app/web ./

EXPOSE 10000

CMD ["npm", "run", "start"]
